### model
model_name_or_path: /media/txshi/新加卷/Models/Qwen1.5-1.8B-Chat/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: wechat_translation
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: qwen1.5-1.8B-Chat-wechat-lora
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 5.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: qwen1.5-1.8B-Chat-wechat-lora/checkpoint-5000/

### eval
val_size: 0.01
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 200
